repos:
  # Add the pre-commit-terraform repository and specify the hooks to enable
  # Get the latest from https://github.com/antonbabenko/pre-commit-terraform/releases
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      # Install tflint by following the guide https://github.com/terraform-linters/tflint
      - id: terraform_tflint
      # Install tfsec by following the guide https://github.com/aquasecurity/tfsec
      - id: terraform_tfsec
      # Install tfupdate by following the guide https://github.com/minamijoyo/tfupdate
      - id: tfupdate

  # Add the pre-commit-hooks repository and specify the hooks to enable
  # Get the latest from https://github.com/pre-commit/pre-commit-hooks/releases
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
